"""Items addition

Revision ID: 4c50c0342d2c
Revises: c10103a0046f
Create Date: 2025-02-20 18:41:18.510563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c50c0342d2c'
down_revision: Union[str, None] = 'c10103a0046f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_checkout_user_id_user', 'checkout', type_='foreignkey')
    op.drop_column('checkout', 'state')
    op.drop_column('checkout', 'timestamp')
    op.drop_column('checkout', 'user_id')
    op.add_column('receipt', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('receipt', sa.Column('state', sa.String(), server_default='CREATED', nullable=False))
    op.add_column('receipt', sa.Column('timestamp', sa.DateTime(), server_default=sa.text('statement_timestamp()'), nullable=False))
    op.create_foreign_key(op.f('fk_receipt_user_id_user'), 'receipt', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_receipt_user_id_user'), 'receipt', type_='foreignkey')
    op.drop_column('receipt', 'timestamp')
    op.drop_column('receipt', 'state')
    op.drop_column('receipt', 'user_id')
    op.add_column('checkout', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('checkout', sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('statement_timestamp()'), autoincrement=False, nullable=False))
    op.add_column('checkout', sa.Column('state', sa.VARCHAR(), server_default=sa.text("'CREATED'::character varying"), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_checkout_user_id_user', 'checkout', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
